#!/bin/bash

set -e

EXPERIMENT_ID="$1"
DATA_NAME="$2"
DATA_FILE="$3"
W1="$4"
W2="$5"
INNER="$6"
LSD="10"
ALPHA="0.0001"
REHU="0.0001"
SCALE_FX="$7"
BATCH_SIZE="$8"

if [ -z "$EXPERIMENT_ID" ]; then
    echo "NO EXPERIMENT ID"
    exit
elif [ -z "$DATA_FILE" ]; then
    echo "NO DATASET"
    exit
fi

OUTDIR="/experiments/${EXPERIMENT_ID}/${DATA_NAME}_${W1}_${W2}_${INNER}_${ALPHA}_${REHU}_scaled${SCALE_FX}"
MODEL="vae_trajectory[stable,w=$W1,bce=$W2,latent_space_dim=$LSD,a=$ALPHA,projfn=$INNER,h=320,hp=200,rehu=$REHU,scale_fx=${SCALE_FX}]"

mkdir -p "$OUTDIR"
echo $MODEL > "$OUTDIR/model"

date >> "$OUTDIR/progress.txt"
./robo_train.py                      \
    --log-to "/runs/$OUTDIR"                 \
    --batch-size $BATCH_SIZE                        \
    --learning-rate "0.0002"                \
    --epochs 150                            \
    specimagepairs[file=$DATA_FILE]    \
    "$MODEL"                                \
    "$OUTDIR/checkpoint_{epoch:0>5}.pth" | tee -a "$OUTDIR/progress.txt"

./render_robo_vae "$DATA_FILE" "$MODEL" "$OUTDIR"
